# Generated by Django 5.2.17 on 2026-08-31 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload or update your company logo. Recommended: PNG or JPG, max 5MB.', null=True, upload_to='logos/', verbose_name='company logo'),
        ),
    ]
