# Generated by Django 5.2.17 on 2026-08-29 07:56

import django.core.validators
import django.db.models.deletion
import security_cheques.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityCheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('received', 'Received'), ('not_received', 'Not Received'), ('pending', 'Pending'), ('returned', 'Returned')], default='not_received', max_length=20, verbose_name='status')),
                ('cheque_number', models.CharField(blank=True, max_length=100, verbose_name='cheque number')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='amount')),
                ('cheque_date', models.DateField(blank=True, null=True, verbose_name='cheque date')),
                ('file', models.FileField(blank=True, upload_to=security_cheques.models.cheque_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='cheque copy')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='file name')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cheques', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_cheques', to='customers.customer', verbose_name='customer')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_cheques', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'security cheque',
                'verbose_name_plural': 'security cheques',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', 'status'], name='security_ch_custome_d8cc2f_idx'), models.Index(fields=['status'], name='security_ch_status_98e304_idx'), models.Index(fields=['cheque_date'], name='security_ch_cheque__c4a573_idx')],
            },
        ),
    ]
