# Generated by Django 5.2.17 on 2026-08-29 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('report_type', models.CharField(max_length=50, verbose_name='report type')),
                ('filters', models.JSONField(default=dict, verbose_name='filters')),
                ('columns', models.JSONField(default=list, verbose_name='columns')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_public', models.BooleanField(default=False, verbose_name='public')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_templates', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'report template',
                'verbose_name_plural': 'report templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20, verbose_name='frequency')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='last run')),
                ('next_run', models.DateTimeField(blank=True, null=True, verbose_name='next run')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('recipients', models.ManyToManyField(related_name='scheduled_reports', to=settings.AUTH_USER_MODEL, verbose_name='recipients')),
                ('report_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to='reports.reporttemplate', verbose_name='report template')),
            ],
            options={
                'verbose_name': 'scheduled report',
                'verbose_name_plural': 'scheduled reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
