# Generated by Django 5.2.17 on 2026-08-29 07:56

import django.core.validators
import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('trade_license', 'Trade License'), ('passport', 'Passport'), ('emirates_id', 'Emirates ID'), ('trn_certificate', 'TRN Certificate'), ('security_cheque', 'Security Cheque'), ('other', 'Other')], max_length=20, verbose_name='document type')),
                ('file', models.FileField(upload_to=documents.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'xlsx', 'xls'])], verbose_name='file')),
                ('file_name', models.CharField(max_length=255, verbose_name='file name')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='file size')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='expiry date')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='customers.customer', verbose_name='customer')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='uploaded by')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['customer', 'document_type'], name='documents_d_custome_7043fb_idx'), models.Index(fields=['uploaded_at'], name='documents_d_uploade_65506e_idx'), models.Index(fields=['expiry_date'], name='documents_d_expiry__1d702a_idx')],
            },
        ),
    ]
