# Generated by Django 5.2.17 on 2026-08-29 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salespersons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='company name')),
                ('trade_license_number', models.CharField(blank=True, max_length=100, verbose_name='trade license number')),
                ('trade_license_expiry', models.DateField(blank=True, null=True, verbose_name='trade license expiry')),
                ('trn', models.CharField(blank=True, max_length=50, verbose_name='TRN')),
                ('customer_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='active', max_length=20, verbose_name='customer status')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('passport_number', models.CharField(blank=True, max_length=100, verbose_name='passport number')),
                ('passport_expiry', models.DateField(blank=True, null=True, verbose_name='passport expiry')),
                ('eid_number', models.CharField(blank=True, max_length=100, verbose_name='EID number')),
                ('eid_expiry', models.DateField(blank=True, null=True, verbose_name='EID expiry')),
                ('copy_status', models.CharField(choices=[('complete', 'Complete'), ('partial', 'Partial'), ('missing', 'Missing')], default='missing', max_length=20, verbose_name='copy status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('sales_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='salespersons.salesperson', verbose_name='sales person')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_customers', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'customer',
                'verbose_name_plural': 'customers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company_name'], name='customers_c_company_2610e7_idx'), models.Index(fields=['trade_license_number'], name='customers_c_trade_l_817b23_idx'), models.Index(fields=['sales_person'], name='customers_c_sales_p_751dea_idx'), models.Index(fields=['customer_status'], name='customers_c_custome_58dde4_idx'), models.Index(fields=['trade_license_expiry'], name='customers_c_trade_l_7a316d_idx'), models.Index(fields=['passport_expiry'], name='customers_c_passpor_e7f449_idx'), models.Index(fields=['eid_expiry'], name='customers_c_eid_exp_9cbd2a_idx')],
            },
        ),
    ]
