# Generated by Django 5.2.17 on 2026-09-03 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='company_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='company name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='trade_license_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='trade license number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='trn',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='TRN'),
        ),
    ]
