# Generated by Django 5.2.17 on 2026-08-29 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('document_uploaded', 'Document Uploaded'), ('document_updated', 'Document Updated'), ('document_deleted', 'Document Deleted'), ('document_downloaded', 'Document Downloaded'), ('document_viewed', 'Document Viewed'), ('cheque_created', 'Cheque Created'), ('cheque_updated', 'Cheque Updated'), ('cheque_deleted', 'Cheque Deleted'), ('cheque_downloaded', 'Cheque Downloaded'), ('salesperson_created', 'Sales Person Created'), ('salesperson_updated', 'Sales Person Updated'), ('salesperson_deleted', 'Sales Person Deleted'), ('salesperson_toggled', 'Sales Person Toggled'), ('customer_reassigned', 'Customer Reassigned'), ('imported', 'Imported'), ('exported', 'Exported'), ('bulk_updated', 'Bulk Updated')], max_length=30, verbose_name='action')),
                ('description', models.TextField(verbose_name='description')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='timestamp')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('object_type', models.CharField(blank=True, max_length=50, verbose_name='object type')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='object ID')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='changes')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='customers.customer', verbose_name='customer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'audit log',
                'verbose_name_plural': 'audit logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='audit_audit_user_id_ea8c9f_idx'), models.Index(fields=['customer', '-timestamp'], name='audit_audit_custome_52646a_idx'), models.Index(fields=['action', '-timestamp'], name='audit_audit_action_e33994_idx'), models.Index(fields=['-timestamp'], name='audit_audit_timesta_901180_idx')],
            },
        ),
    ]
