# Generated by Django 5.2.17 on 2026-09-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted'), ('document_uploaded', 'Document Uploaded'), ('document_updated', 'Document Updated'), ('document_deleted', 'Document Deleted'), ('document_downloaded', 'Document Downloaded'), ('document_viewed', 'Document Viewed'), ('cheque_created', 'Cheque Created'), ('cheque_updated', 'Cheque Updated'), ('cheque_deleted', 'Cheque Deleted'), ('cheque_downloaded', 'Cheque Downloaded'), ('cheque_bulk_updated', 'Cheques Bulk Updated'), ('salesperson_created', 'Sales Person Created'), ('salesperson_updated', 'Sales Person Updated'), ('salesperson_deleted', 'Sales Person Deleted'), ('salesperson_toggled', 'Sales Person Toggled'), ('salesperson_activated', 'Sales Person Activated'), ('salesperson_deactivated', 'Sales Person Deactivated'), ('customer_reassigned', 'Customer Reassigned'), ('imported', 'Imported'), ('exported', 'Exported'), ('bulk_updated', 'Bulk Updated')], max_length=30, verbose_name='action'),
        ),
    ]
