# Generated by Django 5.2.17 on 2026-08-29 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_expiry_60_days', models.BooleanField(default=True, verbose_name='Email: 60 days expiry')),
                ('email_expiry_30_days', models.BooleanField(default=True, verbose_name='Email: 30 days expiry')),
                ('email_expiry_7_days', models.BooleanField(default=True, verbose_name='Email: 7 days expiry')),
                ('email_expired', models.BooleanField(default=True, verbose_name='Email: Expired')),
                ('email_missing_documents', models.BooleanField(default=True, verbose_name='Email: Missing Documents')),
                ('email_cheque_pending', models.BooleanField(default=True, verbose_name='Email: Cheque Pending')),
                ('in_app_expiry_60_days', models.BooleanField(default=True, verbose_name='In-app: 60 days expiry')),
                ('in_app_expiry_30_days', models.BooleanField(default=True, verbose_name='In-app: 30 days expiry')),
                ('in_app_expiry_7_days', models.BooleanField(default=True, verbose_name='In-app: 7 days expiry')),
                ('in_app_expired', models.BooleanField(default=True, verbose_name='In-app: Expired')),
                ('in_app_missing_documents', models.BooleanField(default=True, verbose_name='In-app: Missing Documents')),
                ('in_app_cheque_pending', models.BooleanField(default=True, verbose_name='In-app: Cheque Pending')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'notification preference',
                'verbose_name_plural': 'notification preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('expiry_60_days', 'Expiring in 60 Days'), ('expiry_30_days', 'Expiring in 30 Days'), ('expiry_7_days', 'Expiring in 7 Days'), ('expired', 'Expired'), ('missing_documents', 'Missing Documents'), ('cheque_pending', 'Cheque Pending')], max_length=30, verbose_name='type')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('message', models.TextField(verbose_name='message')),
                ('document_type', models.CharField(blank=True, max_length=50, verbose_name='document type')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='expiry date')),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('dismissed', 'Dismissed')], default='unread', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='customers.customer', verbose_name='customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status', '-created_at'], name='notificatio_user_id_eebdc7_idx'), models.Index(fields=['customer', '-created_at'], name='notificatio_custome_5fbd22_idx')],
            },
        ),
    ]
